### ISSUE TITLE
Should not illustrate key string containing "."s

### ISSUE THREAD

**Issue by asamuzaK** [piroor/webextensions-lib-l10n#1]
Just a note for compatibility.
Chrome extension won't accept dots(`.`) in message.json key.

Ref [Formats: Locale-Specific Messages - Google Chrome](https://developer.chrome.com/extensions/i18n-messages#field_details "Formats: Locale-Specific Messages - Google Chrome")

**Comment by piroor** [comment]
Thanks, I missed this issue. Examples in README.md are already updated to "."-free, so I close this.
